#!/bin/bash
## Driver for running advent of code solutions
## Author: Chris Menard
##
## 


fullpath() {
    [[ $1 = /* ]] && echo "$1" || echo "$PWD/${1#./}"
}


FULLPATH=$(fullpath "$0")
PROGNAME="${FULLPATH##*/}"
PROGPATH="${FULLPATH%/*}/"

usage() {
    cat <<EOF
usage: ./${PROGNAME} year day input language

       Run the Advent of Code solution written in the specified 'language'
       for a given 'year' and day, with the specified 'input' file
EOF
    exit 1
}

checkinputs() {
    ## Basic imput handling for help messages
    if [[ $1 == "-h" || $1 == "--help" ]]
    then
	usage
	exit 0
    fi
}

## Basic input check for 4 arguments
if [[ $# -ne 4 ]]
then
    echo "ERROR: Incorrect number of arguments"
    usage
    exit 0
fi


## Check for valid year
year="$1"

if [[ $year =~ ^[0-9]{2}$ ]]
then
    year="20$year"
else
    if [[ ! $year =~ ^[0-9]{4}$ ]]
    then
	echo "ERROR: Invalid year"
	usage
	exit 0
    fi
fi

if [[ ! -d "${PROGPATH}${year}" ]]
then
    echo "No code for Advent of Code year $year. Pick a different year"
    exit 0
fi

## Check for valid day
day="$2"
if [[ ! $day =~ ^[0-9]{1,2}$ ]]
then
    echo "ERROR: Invalid day"
    usage
    exit 0
fi

SOLPATH="${PROGPATH}${year}/day${day}/"

if [[ ! -d "${SOLPATH}" ]]
then
   echo "No code for day number $day yet. Check back later"
   exit 0
fi

## Check for valid input file   
input="$3"
if [[ ! -e "${SOLPATH}${input}" ]]
then
    echo "ERROR: Input file does not exist"
    exit 0
fi
